import './globals.css'
import { Inter } from 'next/font/google'
import Navegacion from '@/componentes/Navegacion.jsx'
import { BsSearch } from "react-icons/bs";
import AuthContextProvider from "../context/AuthContext"
import { DataContextProvider } from '@/context/DataContext';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navegacion />
        <section className='contenedor-section'>
          <div className='contenedor-bus'>
            
          </div>
          <div className='contenedor-contenido'>
            <AuthContextProvider>
              <DataContextProvider>

                {children}

             
              </DataContextProvider>
            </AuthContextProvider>
          </div>
        </section>
      </body>
    </html>
  )
  /*<Navegacion />
  <input className='buscador' placeholder='Buscar en libros'></input>
  <button className='buscador-boton'>Buscar</button>
  <BsSearch className='buscador-lupa' />*/
}
